name: Nuget Library Release
description: Composite action that releases a Nuget library on GitHub releases and on Nuget.

branding:
  color: green
  icon: tag

inputs:
  dotnet-version:
    description: .NET version to be used (e.g. 5.x or 5.0.x).
    required: true
  repo-token:
    description: Repository token.
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  publish-dir:
    description: Directory containing the .nupkg file(s).
    required: false
    default: .
  release-title:
    description: User friendly name for this release.
    required: true
  nuget-api-key:
    description: Microsoft Nuget API key.
    required: true
  is-prerelease:
    description: true if this release is a prerelease.
    required: false
    default: 'false'
  additional-release-files:
    description: newline separated glob path list of files to publish on GitHub with the .nupkg
    required: false

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: GitHub Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ inputs.repo-token }}
        title: ${{ inputs.release-title }}
        draft: false
        prerelease: ${{ inputs.is-prerelease == 'true' }}
        files: |
          ${{ inputs.publish-dir }}/*.nupkg
          ${{ inputs.additional-release-files }}
    - name: Nuget Release
      uses: EasyDesk/action-nuget-push@v0.1.0
      with:
        nuget-api-key: ${{ inputs.nuget-api-key }}
        publish-dir: ${{ inputs.publish-dir }}
